[project]
name = "python-starter"
version = "0.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = []

[dependency-groups]
dev = [
    "jupyter",
    "ruff",
]
